### ISSUE TITLE
[PE-D] Long entry shows as grey box

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-4/tp#141] opened 2022-04-01 17:31 UTC
![Screenshot 2022-04-01 at 2.44.51 PM.png](https://raw.githubusercontent.com/jaegarpoon/ped/main/files/6a814409-089d-4c91-a300-3a83af5ced3e.png)

Command entered:
`add n/naaame p/6312896312783612978231912376312876312712368912360326023761230612307812302360231767238061237 e/asg@das a/lol pf/east, 4-room, $99999999999999999999999932189732189712308923101239, $1`

Unable to view user details

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: jaegarpoon/ped#7

**Comment by Ashuh** [comment] 2022-04-01 18:11
The following exception is thrown when the command is entered:
`Caused by: java.lang.NumberFormatException: For input string: "99999999999999999999999932189732189712308923101239"
`

**Comment by waffledood** [comment] 2022-04-08 14:06
Update the regex in `Price.java` to be `"^\\$\\d{1,9}"`

**Comment by waffledood** [comment] 2022-04-08 14:06
Update the regex in `Price.java` to be `"^\\$\\d{1,9}"`

**Comment by waffledood** [comment] 2022-04-08 14:07
closing this should also close #149

**Comment by waffledood** [comment] 2022-04-08 14:07
closing this should also close #149

**Closed** 2022-04-10 03:51 UTC
Labels: type.Bug, severity.Medium
