### ISSUE TITLE
[PE-D] Stats window values doesn't really make sense

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-4/tp#166] opened 2022-04-01 18:33 UTC
Looking at the values displayed, it seems like the value on each section of the pie chart represents number of persons. If that's the case, it doesn't really make sense to have values like `1.0, 2.0, 3.0` as there's no way there's gonna be 0.5 person.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: xMashedxTomatox/ped#8

**Comment by howardwhw2** [comment] 2022-04-01 19:08
Duplicate of #156

**Closed** 2022-04-02 04:31 UTC
Labels: duplicate
