### ISSUE TITLE
[PE-D] Incorrect favourite window name

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-4/tp#150] opened 2022-04-01 17:41 UTC
![image.png](https://raw.githubusercontent.com/xMashedxTomatox/ped/main/files/a695a605-c49e-41c2-971c-770e1859ce5b.png)
The favourite window shown by the fw command has a window name of reminder

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: xMashedxTomatox/ped#5

**Comment by Ashuh** [comment] 2022-04-01 18:02
Duplicate of #153

**Closed** 2022-04-02 06:30 UTC
Labels: duplicate
